[project]
name = "dep-ml-products"
version = "0.0.1"
description = "ML land-cover/gravel classification workflow for Digital Earth Pacific"
requires-python = ">=3.10"
dependencies = [
    "boto3",
    "dask-ml",
    "dea-tools",
    "dep-tools",
    "gdal==3.13.2",
    "scikit-learn==1.5.1",
    "typer"
]

[tool.uv.sources]
dep-tools = { git = "https://github.com/digitalearthpacific/dep-tools.git", tag = "v0.5.3" }

[dependency-groups]
dev = [
    "ipykernel>=7.1.0,<8.0.0",


    "folium>=0.20.0,<0.21.0",
    "mapclassify>=2.0.0,<3.0.0",
    "matplotlib>=3.10.8,<4.0.0",

    # TODO: Add these
    # "pytest>=9.0.2,<10.0.0",
    # "pre-commit>=4.5.1,<5.0.0",
    # "ruff>=0.15.16,<0.16.0",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src"]
